on:
  push:
  pull_request:

name: Build PDF document

jobs:
  build_pdf:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: nextflow_cookbook_1.tex

      - name: Upload PDF to the workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: nextflow_cookbook_1.pdf
          path: nextflow_cookbook_1.pdf

